### ISSUE TITLE
Downloaded file has no newlines or tabs

### ISSUE THREAD

**Issue by AVHon** [m-rei/youtube-opml-exporter-script#2]
Even though the href data is nicely formatted with newlines and indentation, all of it is lost when the file is actually downloaded. This makes it difficult to manually read the file.

**Comment by AVHon** [comment]
The solution appears to be to apply [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to the output of `buildOpmlFile`.

**Comment by m-rei** [comment]
> Even though the href data is nicely formatted with newlines and indentation, all of it is lost when the file is actually downloaded. This makes it difficult to manually read the file.

You can pretty-print the html in a text editor of your choice with the appropriate addons.
The output is meant just for programmatic consumption. I used this in another tool of mine to feed the data into.

> The solution appears to be to apply encodeURIComponent to the output of buildOpmlFile.

Not quite. The way you did it, leads to uri-encoding the entire file!

It turns
> <opml version="1.1"><body>
into
> %3Copml%20version%3D%221.1%22%3E%3Cbody%3E
