### ISSUE TITLE
OPML file only has alphabetically-first 100 subscriptions

### ISSUE THREAD

**Issue by AVHon** [m-rei/youtube-opml-exporter-script#5]
If the youtube account has more than 100 subscriptions, the channel list page loads with only the first 100 on it, in alphabetical order. When the browser scrolls to the bottom of the list, a POST request is triggered from a `continuationItemRenderer`, which causes more (the next 100, I think? my account has more than 100 but less than 200 subscriptions) to be loaded onto the page.

Since this script runs shortly after page load time, it can only see the first 100 subscriptions.

The contents of the script do get all subscriptions if you manually scroll to the bottom of the page, allowing the continuations to load all of the subscriptions onto the page, and then manually run it.

I have 2 ideas for changing the script to circumvent this:

1. When the script loads, check the page to see if there are any `continuationItemRenderer`s, make the POST request that they would make, and wait for the new content to load. Repeat until there are no new `continuationItemRenderer`s, then parse the page for channels.

2. Make the download be manually triggered, with a button on the page or something. Maybe add some language like "download OPML of subscriptions shown on this page". Alternatively, put the button on the bottom of the page, so the you have to scroll to get to it, and will trigger continuation loads when you do that.

**Comment by m-rei** [comment]
I dont have that use-case... I have sub-accounts (split up into domains, like music, finance, gaming, etc.) and none of them is that big. But in general, it would be a nice-to-have.

The easiest solution is to inject a button somewhere into the site with which you can trigger it.

Gimme a second, let me take a look... or feel free to implement it yourself.

**Comment by m-rei** [comment]
@AVHon i have [implemented](https://github.com/m-rei/youtube-opml-exporter-script/commit/e76184fd3301e71c231ecaa260467262f9fe5a67) it!

**Comment by AVHon** [comment]
Awesome! Thank you for the incredibly timely responses today. I just found this script on [reddit](https://www.reddit.com/r/privacy/comments/nnrvui/exporting_your_youtube_subscriptions_as_a_opml/) when searching for a tool to do this. I was able to make it work for me; I'm happy that now it can work better for others!
